# In servers and development these are overidden
# by external application.yml

app:
  baseUrl: https://demo.justus.csc.fi

db:
  host: localhost
  port: 5432
  name: set_me_right
  user: set_me_right
  pass: set_me_right

jooq:
  sql.dialect: POSTGRES

api:
  url.prefix: /api
  public:
    url.prefix: /public

opintopolku:
  baseUrl: https://testi.virkailija.opintopolku.fi
  lokalisaatio:
    restUrl: /lokalisointi/cxf/rest/v1/localisation
  koodisto:
    restUrl: /koodisto-service/rest/json
  organisaatio:
    restUrl: /organisaatio-service/rest/organisaatio

server:
  port: 8090

spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.user}
    password: ${db.pass}
    platform: postgresql
    driverClassName: org.postgresql.Driver
    initialize: false
