
- name: Copy Apache configuration files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.owner }}
  with_items:
    - { src: justus-backend.conf.j2, dest: /etc/httpd/conf.d/justus-backend.conf, mode: "0644", owner: root }

- name: Restart Apache
  service: name=httpd state=restarted